import TEST_IMG from "public/vercel.svg";

export const mockData = [
  {
    storeId: 1,
    name: "코끼리 베이글 서초점",
    address: "서울시 강남구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "1번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T10:00",
    closedTime: "T13:00",
    closedDays: "월요일 휴무",
  },
  {
    storeId: 2,
    name: "베이글 천국 천호점",
    address: "서울시 강동구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "2번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T09:00",
    closedTime: "T21:00",
    closedDays: "일요일 휴무",
  },
  {
    storeId: 3,
    name: "베이글 나라 마곡점",
    address: "서울시 강서구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "3번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T10:00",
    closedTime: "T21:00",
    closedDays: "월요일 휴무",
  },
  {
    storeId: 4,
    name: "4번가게",
    address: "서울시 강북구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "4번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T10:00",
    closedTime: "T21:00",
    closedDays: "월요일 휴무",
  },
  {
    storeId: 5,
    name: "5번가게",
    address: "서울시 강남구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "5번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T10:00",
    closedTime: "T20:00",
    closedDays: "월요일 휴무",
  },
  {
    storeId: 6,
    name: "6번가게",
    address: "서울시 강동구",
    storePictureUrl: TEST_IMG,
    phone: "010-1234-5678",
    content: "6번가게 설명",
    productCreatedTime: "T11:00",
    openedTime: "T09:00",
    closedTime: "T21:00",
    closedDays: "일요일 휴무",
  },
];
